// This file was generated by:
//
// go run generator.go > generated.h
//
// DO NOT EDIT THIS FILE MANUALLY.

// --------

// Copyright 2026 Nigel Tao.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// --------

// clang-format off

#define TOKEN_FOR_0                  0x00200000u
#define TOKEN_FOR_CHAR               0x40800004u
#define TOKEN_FOR_CLASS              0x40A0000Bu
#define TOKEN_FOR_COMPANION          0x41200013u
#define TOKEN_FOR_CONST              0x40A0001Fu
#define TOKEN_FOR_CONSTRUCTOR        0x41600027u
#define TOKEN_FOR_DEFAULT            0x40E00035u
#define TOKEN_FOR_DEFINE             0x40C0003Fu
#define TOKEN_FOR_ELIF               0x40800048u
#define TOKEN_FOR_ELSE               0x4080004Fu
#define TOKEN_FOR_ENDIF              0x40A00056u
#define TOKEN_FOR_ENUM               0x4080005Eu
#define TOKEN_FOR_EXTERN             0x40C00065u
#define TOKEN_FOR_FN                 0x4040006Eu
#define TOKEN_FOR_FOR                0x40600073u
#define TOKEN_FOR_FUN                0x40600079u
#define TOKEN_FOR_FUNC               0x4080007Fu
#define TOKEN_FOR_IF                 0x40400086u
#define TOKEN_FOR_IFDEF              0x40A0008Bu
#define TOKEN_FOR_IFNDEF             0x40C00093u
#define TOKEN_FOR_IMPL               0x4080009Cu
#define TOKEN_FOR_IMPORT             0x40C000A3u
#define TOKEN_FOR_INT                0x406000ACu
#define TOKEN_FOR_INTERFACE          0x412000B2u
#define TOKEN_FOR_MOD                0x406000BEu
#define TOKEN_FOR_NAMESPACE          0x412000C4u
#define TOKEN_FOR_OBJECT             0x40C000D0u
#define TOKEN_FOR_PACKAGE            0x40E000D9u
#define TOKEN_FOR_PUB                0x406000E3u
#define TOKEN_FOR_STRUCT             0x40C000E9u
#define TOKEN_FOR_TRAIT              0x40A000F2u
#define TOKEN_FOR_TYPE               0x408000FAu
#define TOKEN_FOR_UNDEF              0x40A00101u
#define TOKEN_FOR_USE                0x40600109u
#define TOKEN_FOR_USING              0x40A0010Fu
#define TOKEN_FOR_VAL                0x40600117u
#define TOKEN_FOR_VAR                0x4060011Du
#define TOKEN_FOR_VOID               0x40800123u

#define INTERNALIZE_WELL_KNOWN_NAMES() \
  do { \
    internalize("0"                 ,  1, false); \
    internalize("char"              ,  4, true); \
    internalize("class"             ,  5, true); \
    internalize("companion"         ,  9, true); \
    internalize("const"             ,  5, true); \
    internalize("constructor"       , 11, true); \
    internalize("default"           ,  7, true); \
    internalize("define"            ,  6, true); \
    internalize("elif"              ,  4, true); \
    internalize("else"              ,  4, true); \
    internalize("endif"             ,  5, true); \
    internalize("enum"              ,  4, true); \
    internalize("extern"            ,  6, true); \
    internalize("fn"                ,  2, true); \
    internalize("for"               ,  3, true); \
    internalize("fun"               ,  3, true); \
    internalize("func"              ,  4, true); \
    internalize("if"                ,  2, true); \
    internalize("ifdef"             ,  5, true); \
    internalize("ifndef"            ,  6, true); \
    internalize("impl"              ,  4, true); \
    internalize("import"            ,  6, true); \
    internalize("int"               ,  3, true); \
    internalize("interface"         ,  9, true); \
    internalize("mod"               ,  3, true); \
    internalize("namespace"         ,  9, true); \
    internalize("object"            ,  6, true); \
    internalize("package"           ,  7, true); \
    internalize("pub"               ,  3, true); \
    internalize("struct"            ,  6, true); \
    internalize("trait"             ,  5, true); \
    internalize("type"              ,  4, true); \
    internalize("undef"             ,  5, true); \
    internalize("use"               ,  3, true); \
    internalize("using"             ,  5, true); \
    internalize("val"               ,  3, true); \
    internalize("var"               ,  3, true); \
    internalize("void"              ,  4, true); \
  } while (false)

// clang-format on
