// This file was generated by:
//
// go run generator.go > generated.h
//
// DO NOT EDIT THIS FILE MANUALLY.

// --------

// Copyright 2026 Nigel Tao.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

#define g_token_for_0                0x00200000u
#define g_token_for_char             0x40800004u
#define g_token_for_class            0x40A0000Bu
#define g_token_for_const            0x40A00013u
#define g_token_for_default          0x40E0001Bu
#define g_token_for_define           0x40C00025u
#define g_token_for_elif             0x4080002Eu
#define g_token_for_else             0x40800035u
#define g_token_for_endif            0x40A0003Cu
#define g_token_for_enum             0x40800044u
#define g_token_for_extern           0x40C0004Bu
#define g_token_for_fn               0x40400054u
#define g_token_for_for              0x40600059u
#define g_token_for_func             0x4080005Fu
#define g_token_for_if               0x40400066u
#define g_token_for_ifdef            0x40A0006Bu
#define g_token_for_ifndef           0x40C00073u
#define g_token_for_impl             0x4080007Cu
#define g_token_for_import           0x40C00083u
#define g_token_for_int              0x4060008Cu
#define g_token_for_interface        0x41200092u
#define g_token_for_mod              0x4060009Eu
#define g_token_for_namespace        0x412000A4u
#define g_token_for_package          0x40E000B0u
#define g_token_for_pub              0x406000BAu
#define g_token_for_struct           0x40C000C0u
#define g_token_for_trait            0x40A000C9u
#define g_token_for_type             0x408000D1u
#define g_token_for_undef            0x40A000D8u
#define g_token_for_use              0x406000E0u
#define g_token_for_using            0x40A000E6u
#define g_token_for_var              0x406000EEu
#define g_token_for_void             0x408000F4u

#define INTERNALIZE_WELL_KNOWN_NAMES() \
  do { \
    internalize("0"                 ,  1, false); \
    internalize("char"              ,  4, true); \
    internalize("class"             ,  5, true); \
    internalize("const"             ,  5, true); \
    internalize("default"           ,  7, true); \
    internalize("define"            ,  6, true); \
    internalize("elif"              ,  4, true); \
    internalize("else"              ,  4, true); \
    internalize("endif"             ,  5, true); \
    internalize("enum"              ,  4, true); \
    internalize("extern"            ,  6, true); \
    internalize("fn"                ,  2, true); \
    internalize("for"               ,  3, true); \
    internalize("func"              ,  4, true); \
    internalize("if"                ,  2, true); \
    internalize("ifdef"             ,  5, true); \
    internalize("ifndef"            ,  6, true); \
    internalize("impl"              ,  4, true); \
    internalize("import"            ,  6, true); \
    internalize("int"               ,  3, true); \
    internalize("interface"         ,  9, true); \
    internalize("mod"               ,  3, true); \
    internalize("namespace"         ,  9, true); \
    internalize("package"           ,  7, true); \
    internalize("pub"               ,  3, true); \
    internalize("struct"            ,  6, true); \
    internalize("trait"             ,  5, true); \
    internalize("type"              ,  4, true); \
    internalize("undef"             ,  5, true); \
    internalize("use"               ,  3, true); \
    internalize("using"             ,  5, true); \
    internalize("var"               ,  3, true); \
    internalize("void"              ,  4, true); \
  } while (false)
