// Copyright 2026 Nigel Tao.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// --------

//go:build ignore

package main

import (
	"fmt"
	"strings"
)

func main() {
	fmt.Printf("%s\n", preamble)

	n := uint32(0)
	for _, s := range wellKnownNames {
		value := (uint32(len(s)) << 21) | n
		if !isIntegery(s) {
			value |= 0x40000000
		}

		fmt.Printf("#define %-28s 0x%08Xu\n",
			"TOKEN_FOR_"+strings.ToUpper(s), value)

		n += 3 + uint32(len(s))
	}

	fmt.Printf("\n")
	fmt.Printf("#define INTERNALIZE_WELL_KNOWN_NAMES() \\\n")
	fmt.Printf("  do { \\\n")

	for _, s := range wellKnownNames {
		fmt.Printf("    internalize(%-20q, %2d, %t); \\\n",
			s, len(s), !isIntegery(s))
	}

	fmt.Printf("  } while (false)\n")
	fmt.Printf("\n")
	fmt.Printf("// clang-format on\n")
}

func isIntegery(s string) bool {
	for _, r := range s {
		if (r < '0') || ('9' < r) {
			return false
		}
	}
	return true
}

const preamble = `// This file was generated by:
//
// go run generator.go > generated.h
//
// DO NOT EDIT THIS FILE MANUALLY.

// --------

// Copyright 2026 Nigel Tao.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// --------

// clang-format off
`

var wellKnownNames = []string{
	"0",
	"char",
	"class",
	"companion",
	"const",
	"default",
	"define",
	"elif",
	"else",
	"endif",
	"enum",
	"extern",
	"fn",
	"for",
	"fun",
	"func",
	"if",
	"ifdef",
	"ifndef",
	"impl",
	"import",
	"int",
	"interface",
	"mod",
	"namespace",
	"object",
	"package",
	"pub",
	"struct",
	"trait",
	"type",
	"undef",
	"use",
	"using",
	"val",
	"var",
	"void",
}
